from __future__ import annotations

# Comprehensive Forex, technical analysis, risk management and MetaTrader
# curriculum. This is an educational curriculum, not trading advice.

FOREX_CURRICULUM = [
    {"order": 1, "topic": "Forex fundamentals", "goal": "What the foreign-exchange market is, participants, trading venues, terminology and market mechanics"},
    {"order": 2, "topic": "Currency pairs", "goal": "Base and quote currencies, majors, minors, exotics and pair conventions"},
    {"order": 3, "topic": "Pips points ticks and price precision", "goal": "Pips, points, tick size, decimal pricing and pip-value concepts"},
    {"order": 4, "topic": "Lots and position size", "goal": "Standard, mini and micro lots, units, contract size and position sizing concepts"},
    {"order": 5, "topic": "Spread commission and trading costs", "goal": "Bid/ask spread, commissions, swaps, slippage and total transaction cost"},
    {"order": 6, "topic": "Leverage and margin", "goal": "Leverage, initial margin, maintenance margin, free margin and liquidation concepts"},
    {"order": 7, "topic": "Orders and execution", "goal": "Market, limit, stop, stop-limit, pending orders, execution and slippage"},
    {"order": 8, "topic": "Stop loss and take profit", "goal": "Protective stops, targets, placement logic and execution limitations"},
    {"order": 9, "topic": "Liquidity and volatility", "goal": "Liquidity, volatility, spreads, market depth concepts and regime changes"},
    {"order": 10, "topic": "Forex sessions and market hours", "goal": "Asian, London and New York sessions, overlaps, liquidity cycles and session behavior"},
    {"order": 11, "topic": "Brokers and execution models", "goal": "Broker roles, execution models, quotes, order routing and operational due diligence"},
    {"order": 12, "topic": "Fundamental macroeconomics", "goal": "Growth, inflation, employment, interest rates, monetary policy and currency valuation concepts"},
    {"order": 13, "topic": "Central banks and interest rates", "goal": "Policy rates, expectations, forward guidance and rate differentials"},
    {"order": 14, "topic": "Economic calendar and news", "goal": "Economic releases, consensus, surprises, event risk and responsible interpretation"},
    {"order": 15, "topic": "Intermarket relationships", "goal": "Rates, bonds, equities, commodities, currencies and correlation concepts"},
    {"order": 16, "topic": "Trading psychology fundamentals", "goal": "Decision processes, discipline, uncertainty, cognitive biases and journaling"},
    {"order": 17, "topic": "Risk management fundamentals", "goal": "Risk per trade, exposure, stop distance, position size and loss limits"},
    {"order": 18, "topic": "Risk reward and expectancy", "goal": "R-multiples, reward-to-risk, win rate, expectancy and distribution of outcomes"},
    {"order": 19, "topic": "Drawdown and risk of ruin", "goal": "Drawdown, recovery, losing streaks, risk of ruin and survival-first thinking"},
    {"order": 20, "topic": "Trading journal and statistics", "goal": "Record trades, classify setups, measure outcomes and identify process errors"},
    {"order": 21, "topic": "Candlestick fundamentals", "goal": "OHLC data, candle anatomy, body, wicks and contextual interpretation"},
    {"order": 22, "topic": "Single-candle patterns", "goal": "Doji, hammer, shooting star, engulfing context and limitations of isolated patterns"},
    {"order": 23, "topic": "Multi-candle patterns", "goal": "Two- and three-candle formations, confirmation and contextual validity"},
    {"order": 24, "topic": "Trend analysis", "goal": "Uptrends, downtrends, ranges, trendlines and structural transitions"},
    {"order": 25, "topic": "Market structure", "goal": "Higher highs, higher lows, lower highs, lower lows and structural context"},
    {"order": 26, "topic": "Support and resistance", "goal": "Horizontal levels, zones, role reversal and validation"},
    {"order": 27, "topic": "Supply and demand zones", "goal": "Zone construction, departure, retests, invalidation and contextual use"},
    {"order": 28, "topic": "Breakouts and false breakouts", "goal": "Breakout structure, confirmation, retests, traps and invalidation"},
    {"order": 29, "topic": "Pullbacks and retests", "goal": "Continuation entries, retracement structure and confirmation"},
    {"order": 30, "topic": "Price action", "goal": "Context-first chart reading, swing points, rejection, momentum and confluence"},
    {"order": 31, "topic": "BOS and CHoCH", "goal": "Break of structure, change of character and disciplined structural interpretation"},
    {"order": 32, "topic": "Liquidity concepts", "goal": "Liquidity pools, equal highs/lows, sweeps, inducement concepts and limitations"},
    {"order": 33, "topic": "Order blocks and imbalance", "goal": "Order-block concepts, fair-value gaps, imbalance and contextual validation"},
    {"order": 34, "topic": "Chart patterns", "goal": "Triangles, flags, pennants, rectangles, wedges and measured-move concepts"},
    {"order": 35, "topic": "Reversal chart patterns", "goal": "Double and triple tops/bottoms, head and shoulders and failure patterns"},
    {"order": 36, "topic": "Harmonic patterns", "goal": "ABCD, Gartley, Bat, Butterfly, Crab and ratio-based validation"},
    {"order": 37, "topic": "Fibonacci retracement", "goal": "Retracement levels, swing selection, confluence and invalidation"},
    {"order": 38, "topic": "Fibonacci extension and projection", "goal": "Targets, extensions, expansions and multi-leg projections"},
    {"order": 39, "topic": "Elliott Wave fundamentals", "goal": "Impulse and corrective structures, wave relationships and uncertainty handling"},
    {"order": 40, "topic": "Advanced Elliott Wave", "goal": "Complex corrections, alternation, invalidation and scenario-based analysis"},
    {"order": 41, "topic": "Moving averages", "goal": "SMA, EMA, WMA, HMA and VWMA calculation and interpretation"},
    {"order": 42, "topic": "Moving-average systems", "goal": "Crossovers, slope, dynamic support/resistance and regime filters"},
    {"order": 43, "topic": "RSI", "goal": "Relative strength, overbought/oversold concepts, divergence and failure swings"},
    {"order": 44, "topic": "MACD", "goal": "EMA difference, signal line, histogram, crossovers and divergence"},
    {"order": 45, "topic": "Stochastic oscillator", "goal": "Oscillator construction, momentum, zones, crossovers and divergence"},
    {"order": 46, "topic": "Bollinger Bands", "goal": "Moving average, standard deviation bands, volatility and squeeze concepts"},
    {"order": 47, "topic": "ATR", "goal": "Average True Range, volatility measurement and volatility-aware stops"},
    {"order": 48, "topic": "ADX and DMI", "goal": "Trend strength, directional movement and regime filtering"},
    {"order": 49, "topic": "CCI", "goal": "Commodity Channel Index, momentum, mean-reversion and trend contexts"},
    {"order": 50, "topic": "Williams %R", "goal": "Momentum oscillator interpretation, zones and confirmation"},
    {"order": 51, "topic": "ROC and Momentum", "goal": "Rate of change, momentum measurement and comparative interpretation"},
    {"order": 52, "topic": "Ichimoku", "goal": "Tenkan-sen, Kijun-sen, Senkou spans, Chikou and cloud-based context"},
    {"order": 53, "topic": "Parabolic SAR", "goal": "Trend-following dots, acceleration factor, reversals and limitations"},
    {"order": 54, "topic": "OBV", "goal": "On-balance volume, accumulation/distribution concepts and divergence"},
    {"order": 55, "topic": "MFI", "goal": "Money Flow Index, price-volume interaction and momentum interpretation"},
    {"order": 56, "topic": "CMF and ADL", "goal": "Chaikin Money Flow, accumulation/distribution line and volume-pressure concepts"},
    {"order": 57, "topic": "VWAP", "goal": "Volume-weighted average price, anchored concepts and session context"},
    {"order": 58, "topic": "Pivot points", "goal": "Classic pivot calculations, support/resistance levels and session planning"},
    {"order": 59, "topic": "Donchian channels", "goal": "High-low channels, breakout systems and trend-following applications"},
    {"order": 60, "topic": "Keltner channels", "goal": "ATR-based channels, trend and volatility context"},
    {"order": 61, "topic": "Envelopes and volatility bands", "goal": "Percentage bands, deviation concepts and mean-reversion context"},
    {"order": 62, "topic": "Alligator and Awesome Oscillator", "goal": "Bill Williams indicator family, momentum and trend context"},
    {"order": 63, "topic": "Accelerator Oscillator", "goal": "Momentum acceleration concepts and contextual interpretation"},
    {"order": 64, "topic": "Standard deviation and volatility tools", "goal": "Dispersion, volatility regimes and statistical chart context"},
    {"order": 65, "topic": "Indicator divergence", "goal": "Regular and hidden divergence, confirmation, failure modes and testing"},
    {"order": 66, "topic": "Indicator confluence", "goal": "Combine independent evidence without double-counting correlated signals"},
    {"order": 67, "topic": "Multi-timeframe analysis", "goal": "Top-down analysis, alignment, conflicts and timeframe selection"},
    {"order": 68, "topic": "Trend-following strategies", "goal": "Rule-based trend systems using structure, momentum and volatility"},
    {"order": 69, "topic": "Mean-reversion strategies", "goal": "Range detection, deviation, confirmation and failure conditions"},
    {"order": 70, "topic": "Breakout strategies", "goal": "Range compression, breakout confirmation, retest and risk control"},
    {"order": 71, "topic": "Momentum strategies", "goal": "Momentum identification, continuation and exit logic"},
    {"order": 72, "topic": "Scalping systems", "goal": "Short-horizon system design, execution costs, spread sensitivity and testing"},
    {"order": 73, "topic": "Swing trading systems", "goal": "Multi-session setups, structural stops, targets and trade management"},
    {"order": 74, "topic": "Position trading systems", "goal": "Longer-horizon macro and technical frameworks, exposure and carry considerations"},
    {"order": 75, "topic": "Strategy engineering", "goal": "Turn trading ideas into explicit, testable rules and machine-readable conditions"},
    {"order": 76, "topic": "Entry and exit engineering", "goal": "Define triggers, confirmations, invalidation, stop, target and exit rules"},
    {"order": 77, "topic": "Dynamic stop and target systems", "goal": "ATR-based, structure-based, volatility-based and trailing exit models"},
    {"order": 78, "topic": "Position sizing systems", "goal": "Fixed risk, volatility-adjusted sizing, portfolio exposure and constraints"},
    {"order": 79, "topic": "Backtesting fundamentals", "goal": "Historical data, assumptions, costs, execution models and reproducible tests"},
    {"order": 80, "topic": "Backtest quality and bias control", "goal": "Look-ahead bias, survivorship bias, data snooping, leakage and realistic assumptions"},
    {"order": 81, "topic": "Performance metrics", "goal": "Win rate, expectancy, profit factor, drawdown, Sharpe, Sortino and recovery factor"},
    {"order": 82, "topic": "Walk-forward analysis", "goal": "Rolling training and validation windows, robustness and parameter stability"},
    {"order": 83, "topic": "Out-of-sample testing", "goal": "Separate development and validation data and evaluate generalization"},
    {"order": 84, "topic": "Parameter optimization", "goal": "Grid search, sensitivity, constraints and avoiding curve fitting"},
    {"order": 85, "topic": "Monte Carlo analysis", "goal": "Resampling trade sequences, drawdown distributions and robustness analysis"},
    {"order": 86, "topic": "Statistical trading analysis", "goal": "Distributions, hypothesis concepts, confidence, sampling and uncertainty"},
    {"order": 87, "topic": "Correlation and portfolio risk", "goal": "Pair correlation, exposure aggregation and concentration risk"},
    {"order": 88, "topic": "Advanced risk management", "goal": "Portfolio risk, risk budgets, Kelly concepts, risk of ruin and stress testing"},
    {"order": 89, "topic": "Market regime detection", "goal": "Trend, range, volatility and adaptive strategy selection"},
    {"order": 90, "topic": "Algorithmic trading architecture", "goal": "Data, signals, execution, risk, state management, logging and fault isolation"},
    {"order": 91, "topic": "MQL4 fundamentals", "goal": "MetaEditor, MQL4 syntax, types, variables, operators and program structure"},
    {"order": 92, "topic": "MQL4 control flow and functions", "goal": "Conditions, loops, functions, arrays, structures and reusable code"},
    {"order": 93, "topic": "MQL4 time series and price data", "goal": "Bars, timeseries arrays, OHLC data, shifts and timeframe access"},
    {"order": 94, "topic": "MQL4 built-in indicators", "goal": "Use and combine moving averages, RSI, MACD, ATR and other indicator APIs"},
    {"order": 95, "topic": "MQL4 custom indicators", "goal": "Indicator buffers, calculations, plotting, inputs and custom signals"},
    {"order": 96, "topic": "MQL4 scripts", "goal": "One-shot automation, chart utilities, data processing and safe script design"},
    {"order": 97, "topic": "MQL4 Expert Advisors", "goal": "EA lifecycle, entry logic, order management, state and event-driven execution"},
    {"order": 98, "topic": "MQL4 trade management", "goal": "Orders, tickets, stop/target handling, trailing logic, errors and retries"},
    {"order": 99, "topic": "MQL4 risk engine", "goal": "Position sizing, margin checks, exposure limits and defensive trade validation"},
    {"order": 100, "topic": "MQL4 multi-timeframe systems", "goal": "Cross-timeframe data, synchronization, confirmation and state management"},
    {"order": 101, "topic": "MQL4 backtesting and optimization", "goal": "Strategy Tester, modeling assumptions, parameters, reports and robustness checks"},
    {"order": 102, "topic": "MQL5 fundamentals", "goal": "MetaEditor, MQL5 syntax, types, objects, events and program architecture"},
    {"order": 103, "topic": "MQL5 time series and indicator handles", "goal": "Series data, indicator handles, buffers, CopyBuffer and synchronization"},
    {"order": 104, "topic": "MQL5 custom indicators", "goal": "Buffers, plots, calculation lifecycle, inputs and advanced indicator design"},
    {"order": 105, "topic": "MQL5 scripts and services", "goal": "Scripts, services, event models and safe automation patterns"},
    {"order": 106, "topic": "MQL5 Expert Advisors", "goal": "EA lifecycle, OnInit, OnTick, events, state and architecture"},
    {"order": 107, "topic": "MQL5 orders deals and positions", "goal": "MT5 order/deal/position model, netting, hedging and trade requests"},
    {"order": 108, "topic": "MQL5 trade classes", "goal": "Standard trade classes, validation, execution, errors and transaction events"},
    {"order": 109, "topic": "MQL5 risk engine", "goal": "Dynamic position sizing, margin checks, exposure limits and portfolio constraints"},
    {"order": 110, "topic": "MQL5 multi-symbol systems", "goal": "Multiple symbols, synchronized data, state isolation and portfolio logic"},
    {"order": 111, "topic": "MQL5 backtesting and optimization", "goal": "Strategy Tester modes, optimization, forward testing and robustness analysis"},
    {"order": 112, "topic": "Custom trading dashboards", "goal": "Charts, panels, metrics, controls, state and safe user interaction"},
    {"order": 113, "topic": "News and session filters in EAs", "goal": "Calendar/event filters, session windows, spread checks and defensive execution"},
    {"order": 114, "topic": "Advanced EA architecture", "goal": "Modular signal, risk, execution, portfolio, logging and configuration layers"},
    {"order": 115, "topic": "Algorithmic execution", "goal": "Execution state machines, retries, slippage, latency and failure handling"},
    {"order": 116, "topic": "Robustness engineering for trading systems", "goal": "Stress tests, parameter perturbation, execution variation and failure scenarios"},
    {"order": 117, "topic": "Quantitative strategy research", "goal": "Research workflow, feature construction, statistical validation and reproducibility"},
    {"order": 118, "topic": "Advanced portfolio construction", "goal": "Allocation, correlation-aware exposure, risk budgets and portfolio-level constraints"},
    {"order": 119, "topic": "Production trading-system engineering", "goal": "Versioning, configuration, logging, monitoring, recovery and operational safeguards"},
    {"order": 120, "topic": "Professional capital management", "goal": "Advanced account-level capital allocation, risk budgeting, exposure limits, compounding, drawdown control, portfolio heat, leverage discipline, scenario stress testing and long-horizon capital preservation"},
    {"order": 121, "topic": "Forex and MetaTrader expert capstone", "goal": "Design, implement, test, document and robustly validate a complete educational algorithmic trading system"},
]

FOREX_SOURCES = [
    "https://www.metatrader4.com/en/trading-platform/help",
    "https://www.metatrader5.com/en/terminal/help",
    "https://www.mql5.com/en/docs",
    "https://www.mql5.com/en/docs/basis",
    "https://www.mql5.com/en/docs/standardlibrary",
    "https://www.mql4.com/en/docs",
    "https://www.investopedia.com/forex-4427685",
    "https://www.cmegroup.com/education/courses/introduction-to-fx.html",
]

FOREX_ALIASES = {
    "forex": "Forex",
    "forex trading": "Forex",
    "fx": "Forex",
    "fx trading": "Forex",
    "فارکس": "Forex",
    "آموزش فارکس": "Forex",
    "بازار فارکس": "Forex",
    "ترید فارکس": "Forex",
    "متاتریدر": "Forex",
    "mql4": "Forex",
    "mql5": "Forex",
    "mql": "Forex",
}
