from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROJECTS_ROOT = ROOT / "projects"
SELF_REPAIR_ROOT = ROOT / "self-repair"

PROJECTS_ROOT.mkdir(parents=True, exist_ok=True)
SELF_REPAIR_ROOT.mkdir(parents=True, exist_ok=True)


def project_slug(name: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9\u0600-\u06ff\u4e00-\u9fff._ -]+", "-", name.strip())
    value = re.sub(r"\s+", "-", value)
    value = re.sub(r"-{2,}", "-", value).strip("-.")
    return (value or "project")[:80]


def create_project_workspace(name: str) -> Path:
    slug = project_slug(name)
    base = PROJECTS_ROOT / slug
    if not base.exists():
        base.mkdir(parents=True)
        return base
    index = 2
    while True:
        candidate = PROJECTS_ROOT / f"{slug}-{index}"
        if not candidate.exists():
            candidate.mkdir(parents=True)
            return candidate
        index += 1


def write_project_files(workspace: Path, language: str, request: str, code: str) -> list[str]:
    workspace = workspace.resolve()
    workspace.relative_to(PROJECTS_ROOT.resolve())

    files: dict[str, str] = {
        "README.md": (
            f"# {workspace.name}\n\n"
            f"Generated by My-AI.\n\n"
            f"Language: {language}\n\n"
            f"Request: {request}\n"
        )
    }
    filename = "main.py" if language.lower() == "python" else "main.txt"
    files[filename] = code

    written = []
    for relative, content in files.items():
        target = (workspace / relative).resolve()
        target.relative_to(workspace)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(str(target.relative_to(workspace.parents[1])).replace("\\", "/"))
    return written
