from __future__ import annotations

import os
import re
from pathlib import Path
from .config import assert_write_allowed

ROOT = Path(__file__).resolve().parent.parent
PROJECTS_ROOT = ROOT / "projects"
SELF_REPAIR_ROOT = ROOT / "self-repair"

if not __import__("os").getenv("MYAI_READ_ONLY", "false").strip().lower() == "true":
    PROJECTS_ROOT.mkdir(parents=True, exist_ok=True)
    SELF_REPAIR_ROOT.mkdir(parents=True, exist_ok=True)


def project_slug(name: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9\u0600-\u06ff\u4e00-\u9fff._ -]+", "-", name.strip())
    value = re.sub(r"\s+", "-", value)
    value = re.sub(r"-{2,}", "-", value).strip("-.")
    return (value or "project")[:80]


def resolve_projects_root(project_path: str | Path | None = None) -> Path:
    """Resolve a user-requested project directory without allowing arbitrary filesystem writes."""
    configured = os.getenv("MYAI_PROJECT_ROOT", "").strip()
    allowed_roots = [PROJECTS_ROOT.resolve(), ROOT.resolve()]
    if configured:
        allowed_roots.append(Path(configured).expanduser().resolve())

    if not project_path:
        return PROJECTS_ROOT.resolve()

    raw = Path(str(project_path)).expanduser()
    candidate = raw.resolve() if raw.is_absolute() else (ROOT / raw).resolve()
    if not any(candidate == root or root in candidate.parents for root in allowed_roots):
        raise ValueError("Project path must stay inside the My-AI project workspace.")
    candidate.mkdir(parents=True, exist_ok=True)
    assert_write_allowed(str(candidate))
    return candidate


def create_project_workspace(name: str, projects_root: str | Path | None = None) -> Path:
    base_root = resolve_projects_root(projects_root)
    assert_write_allowed(str(base_root))
    slug = project_slug(name)
    base = base_root / slug
    if not base.exists():
        base.mkdir(parents=True)
        return base
    index = 2
    while True:
        candidate = base_root / f"{slug}-{index}"
        if not candidate.exists():
            candidate.mkdir(parents=True)
            return candidate
        index += 1


def write_project_files(workspace: Path, language: str, request: str, code: str) -> list[str]:
    assert_write_allowed(str(workspace))
    workspace = workspace.resolve()
    workspace.relative_to(PROJECTS_ROOT.resolve())

    files: dict[str, str] = {
        "README.md": (
            f"# {workspace.name}\n\n"
            f"Generated by My-AI.\n\n"
            f"Language: {language}\n\n"
            f"Request: {request}\n"
        )
    }
    filename = "main.py" if language.lower() == "python" else ("main.mq4" if language.lower() in {"mql4", "mq4"} else "main.txt")
    files[filename] = code

    written = []
    for relative, content in files.items():
        target = (workspace / relative).resolve()
        target.relative_to(workspace)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(str(target.relative_to(workspace.parents[1])).replace("\\", "/"))
    return written
