function byId(id){return document.getElementById(id)}
async function req(url,opt){var r=await fetch(url,opt||{});var text=await r.text();var j={};try{j=JSON.parse(text)}catch(e){throw Error('پاسخ نامعتبر از سرور (HTTP '+r.status+')')}if(!r.ok)throw Error(j.detail||j.message||('HTTP '+r.status));return j}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function setText(id,value){var e=byId(id);if(e)e.textContent=value}
async function loadUsers(){var box=byId('users');if(!box)return;box.textContent='در حال بارگذاری...';try{var j=await req('/settings/users');var items=j.items||[];box.innerHTML=items.map(function(u){return '<div class="topic"><b>'+esc(u.username)+'</b> — '+esc(u.display_name||'بدون نام')+' — نقش: '+esc(u.role)+' — '+(u.active?'فعال':'غیرفعال')+(u.role==='admin'?'':' <button type="button" onclick="toggleUser('+u.id+','+(!u.active)+')">'+(u.active?'غیرفعال‌کردن':'فعال‌کردن')+'</button>')+'</div>'}).join('')||'کاربری ثبت نشده است'}catch(e){box.textContent='خطا در بارگذاری کاربران: '+e.message}}
async function toggleUser(id,active){try{await req('/admin/users/'+id+'/active?active='+active,{method:'PATCH'});await loadUsers()}catch(e){setText('userout',e.message)}}
async function addUser(){try{var j=await req('/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:byId('nu').value,password:byId('np').value,display_name:byId('nd').value,active:true})});setText('userout','کاربر ایجاد شد: '+j.user.username);byId('nu').value='';byId('np').value='';byId('nd').value='';loadUsers();loadPermissions()}catch(e){setText('userout',e.message)}}
async function loadSettings(){try{var j=await req('/settings/config');byId('apiurl').value=j.github.api_url||'';byId('repo').value=j.github.repository||'';byId('ghuser').value=j.github.username||'';byId('su_enabled').checked=!!j.features.self_update_enabled;byId('su_approved').checked=!!j.features.self_update_approved;byId('su_health').value=j.features.self_update_health_url||'';byId('sr_enabled').checked=!!j.features.self_repair_enabled;byId('sr_approval').checked=!!j.features.self_repair_require_approval;byId('lf_enabled').checked=!!j.features.learning_fast_enabled;byId('lf_interval').value=j.features.learning_interval_seconds;byId('lf_retries').value=j.features.learning_max_retries;byId('cpu_percent').value=j.resources.cpu_percent;byId('cpu_threads').value=j.resources.cpu_threads;byId('ram_percent').value=j.resources.ram_percent;byId('gpu_layers').value=j.resources.gpu_layers;setText('gitout',j.github.token_configured?'Token تنظیم شده است':'Token تنظیم نشده است');setText('resourceout','مقادیر فعال: CPU '+j.resources.cpu_percent+'% · '+j.resources.cpu_threads+' thread · RAM '+j.resources.ram_percent+'% · GPU '+j.resources.gpu_layers+' layer')}catch(e){setText('gitout','خطا در بارگذاری تنظیمات: '+e.message)}}
async function saveGithubConfig(){try{await req('/settings/github',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_url:byId('apiurl').value.trim(),repository:byId('repo').value.trim(),username:byId('ghuser').value.trim()})});setText('gitout','تنظیمات GitHub ذخیره شد')}catch(e){setText('gitout',e.message)}}
async function saveToken(){try{var j=await req('/settings/github-token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:byId('token').value})});setText('gitout',j.authenticated?'Token معتبر و متصل به @'+j.login:'Token حذف شد');byId('token').value='';loadSettings()}catch(e){setText('gitout',e.message)}}
async function checkGit(){try{var j=await req('/git/check');setText('gitout',j.message||j.status||'بررسی انجام شد')}catch(e){setText('gitout','خطا در بررسی اتصال: '+e.message)}}
async function saveFeatures(){try{await req('/settings/features',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({self_update_enabled:byId('su_enabled').checked,self_update_approved:byId('su_approved').checked,self_update_health_url:byId('su_health').value,self_repair_enabled:byId('sr_enabled').checked,self_repair_require_approval:byId('sr_approval').checked,learning_fast_enabled:byId('lf_enabled').checked,learning_interval_seconds:Number(byId('lf_interval').value||3600),learning_max_retries:Number(byId('lf_retries').value||5)})});setText('suout','تنظیمات ذخیره شد');setText('srout','تنظیمات ذخیره شد');setText('lfout','تنظیمات ذخیره شد');loadSettings()}catch(e){setText('suout',e.message);setText('srout',e.message);setText('lfout',e.message)}}
window.saveResources=window.saveResources=async function saveResources(){try{var payload={cpu_percent:Number(byId('cpu_percent').value||70),cpu_threads:Number(byId('cpu_threads').value||8),ram_percent:Number(byId('ram_percent').value||80),gpu_layers:Number(byId('gpu_layers').value||0)};var j=await req('/settings/resources',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});byId('cpu_percent').value=j.resources.cpu_percent;byId('cpu_threads').value=j.resources.cpu_threads;byId('ram_percent').value=j.resources.ram_percent;byId('gpu_layers').value=j.resources.gpu_layers;setText('resourceout','مقادیر فعال: CPU '+j.resources.cpu_percent+'% · '+j.resources.cpu_threads+' thread · RAM '+j.resources.ram_percent+'% · GPU '+j.resources.gpu_layers+' layer')}catch(e){setText('resourceout','خطا در ذخیره منابع: '+e.message)}}
var PERM_TOOLS=['chat','code-generation','code-execution','learning','scheduler','github','security','database','voice','models','memory','web','projects','eval','self-update','self-repair','help','tools'];
function permissionCell(uid,tool,action,allowed){return '<label style="display:inline-block;margin:3px"><input type="checkbox" '+(allowed?'checked':'')+' onchange="setPermission('+uid+',\''+tool+'\',\''+action+'\',this.checked)"> '+tool+':'+action+'</label>'}
async function loadPermissions(){var box=byId('permissions');if(!box)return;box.textContent='در حال بارگذاری...';try{var pair=await Promise.all([req('/settings/users'),req('/settings/tool-permissions')]);var usersList=pair[0].items||[];var items=pair[1].items||[];var map={};items.forEach(function(x){map[x.user_id+':'+x.tool_name+':'+x.action]=!!x.allowed});box.innerHTML=usersList.map(function(user){var html='<div class="topic"><b>'+esc(user.username)+'</b> — '+esc(user.role)+'<div>';PERM_TOOLS.forEach(function(tool){['read','write','execute'].forEach(function(action){html+=permissionCell(user.id,tool,action,!!map[user.id+':'+tool+':'+action])})});return html+'</div></div>'}).join('')||'کاربری ثبت نشده است'}catch(e){box.textContent='خطا در بارگذاری مجوزها: '+e.message}}
async function setPermission(uid,tool,action,allowed){try{await req('/settings/tool-permissions',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:uid,tool_name:tool,action:action,allowed:allowed})})}catch(e){alert('خطا در ذخیره مجوز: '+e.message);loadPermissions()}}
async function loginGit(){try{var j=await req('/git/login',{method:'POST'});setText('gitout',j.message||'درخواست ورود ارسال شد')}catch(e){setText('gitout',e.message)}}
async function logoutGit(){try{var j=await req('/git/logout',{method:'POST'});setText('gitout',j.message||'خروج انجام شد');loadSettings()}catch(e){setText('gitout',e.message)}}
async function createCourse(){try{var lines=byId('ct').value.split(/\n+/).map(function(x){return x.trim()}).filter(Boolean);var topics=lines.map(function(x){var p=x.split('|').map(function(v){return v.trim()});return {title:p[0],goal:p[1]||'',source_url:p[2]||''}});var j=await req('/settings/courses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:byId('cn').value,description:byId('cd').value,topics:topics})});setText('courseout','آموزش ساخته شد: '+j.id);loadCourses()}catch(e){setText('courseout',e.message)}}
async function startCourse(id){try{await req('/settings/courses/'+id+'/start',{method:'POST'});loadCourses()}catch(e){setText('courseout',e.message)}}
async function loadCourses(){var box=byId('courses');if(!box)return;try{var j=await req('/settings/courses');box.innerHTML=(j.items||[]).map(function(c){return '<div class="card"><h3>'+esc(c.name)+'</h3><p>'+esc(c.description)+'</p><div class="bar"><div class="fill" style="width:'+c.progress_percent+'%">'+c.progress_percent+'%</div></div><p class="muted">'+c.completed_topics+' از '+c.total_topics+' سرفصل کامل شده'+(c.current?' · اکنون: '+esc(c.current.title)+' · مرحله: '+esc(c.current.phase):'')+'</p><button type="button" onclick="startCourse('+c.id+')">شروع/ادامه یادگیری</button></div>'}).join('')||'آموزشی نیست'}catch(e){box.textContent='خطا در بارگذاری آموزش‌ها: '+e.message}}
loadSettings();loadUsers();loadPermissions();loadCourses();setInterval(loadCourses,10000)