HTML="""<!doctype html><html lang='fa' dir='rtl'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>My-AI</title><style>
body{font-family:Tahoma,system-ui;margin:0;background:#f3f4f6;color:#17202a}main{max-width:1050px;margin:auto;padding:20px}.card{background:#fff;padding:18px;border-radius:14px;margin:12px 0}button{padding:10px 15px;border:0;border-radius:9px;cursor:pointer}textarea{width:100%;box-sizing:border-box;padding:12px;margin:8px 0;border:1px solid #ccc;border-radius:9px}#messages{height:400px;overflow:auto;background:#f8fafc;padding:10px}.msg{padding:9px;margin:7px;border-radius:9px;white-space:pre-wrap}.user{background:#dbeafe}.ai{background:#e5e7eb}pre{white-space:pre-wrap;background:#111827;color:#fff;padding:12px;direction:ltr;text-align:left}.bar{height:24px;background:#ddd;border-radius:8px;overflow:hidden}.fill{height:100%;background:#2563eb;color:#fff;text-align:center;line-height:24px}</style></head><body><main>
<h1>My-AI</h1><p>دستیار محلی برای گفتگو، یادگیری و برنامه‌نویسی</p>
<div class='card'><h2>چت و دستیار صوتی</h2><div id='messages'></div><textarea id='msg' rows='3' placeholder='مثلاً: پایتون را یاد بگیر / یک برنامه بنویس'></textarea><button onclick='send()'>ارسال</button> <button onclick='voiceInput()'>Voice</button> <button onclick='stopVoice()'>Stop</button><p>ورودی و خروجی صوتی با قابلیت‌های مرورگر انجام می‌شود.</p></div>
<div class='card'><h2>پیشرفت یادگیری</h2><div id='dashboard'>در حال بارگذاری...</div></div>
<div class='card'><h2>یادگیری سریع</h2><button onclick="learn('Python')">Python</button> <button onclick="learn('C')">C</button><pre id='learnout'></pre></div>
<script>
var recognition=null;
function $(id){return document.getElementById(id)}
function add(t,w){var d=document.createElement('div');d.className='msg '+w;d.textContent=t;$('messages').appendChild(d);$('messages').scrollTop=999999}
async function post(p,b){var r=await fetch(p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});var j=await r.json();if(!r.ok)throw Error(j.detail||'Request failed');return j}
async function send(){var m=$('msg').value.trim();if(!m)return;add(m,'user');$('msg').value='';try{var j=await post('/chat',{message:m});var a=j.answer||'';if(j.type==='code'&&j.data)a+='\\n\\n'+j.data.code;if(j.type==='learning')a+='\\n'+JSON.stringify(j.data);add(a,'ai');speak(a);loadDash()}catch(e){add(String(e),'ai')}}
function voiceInput(){var SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){add('Speech Recognition در این مرورگر پشتیبانی نمی‌شود.','ai');return}recognition=new SR();recognition.lang='fa-IR';recognition.interimResults=false;recognition.onresult=function(e){$('msg').value=e.results[0][0].transcript;send()};recognition.onerror=function(e){add('خطای صوتی: '+e.error,'ai')};recognition.start()}
function stopVoice(){if(recognition)recognition.stop();if(window.speechSynthesis)speechSynthesis.cancel()}
function speak(t){if(window.speechSynthesis){speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(t);u.lang='fa-IR';speechSynthesis.speak(u)}}
async function learn(lang){$('learnout').textContent='...';try{$('learnout').textContent=JSON.stringify(await post('/learning/step',{language:lang}),null,2);loadDash()}catch(e){$('learnout').textContent=String(e)}}
async function loadDash(){try{var j=await (await fetch('/learning/status')).json(),rows=j.languages||[],h='<table><tr><th>زبان</th><th>موضوعات</th><th>درصد</th><th>میانگین</th></tr>';rows.forEach(function(x){h+='<tr><td>'+x.language+'</td><td>'+x.completed_topics+'/'+x.total_topics+'</td><td>'+x.progress_percent+'%<div class="bar"><div class="fill" style="width:'+x.progress_percent+'%">'+x.progress_percent+'%</div></div></td><td>'+x.average_score+'%</td></tr>'});h+='</table><h3>نمودار پیشرفت</h3>';rows.forEach(function(x){h+='<p>'+x.language+' — '+x.progress_percent+'%</p><div class="bar"><div class="fill" style="width:'+x.progress_percent+'%">'+x.progress_percent+'%</div></div>'});$('dashboard').innerHTML=h}catch(e){$('dashboard').textContent=String(e)}}loadDash();
</script></main></body></html>"""
def page(): return HTML
