HTML="""<!doctype html><html lang='fa' dir='rtl'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>My-AI</title><style>
body{font-family:Tahoma,system-ui;margin:0;background:#f3f4f6;color:#17202a}main{max-width:1100px;margin:auto;padding:20px}.card{background:#fff;padding:18px;border-radius:14px;margin:12px 0}button,select{padding:10px 15px;border:0;border-radius:9px;cursor:pointer;margin:3px}textarea{width:100%;box-sizing:border-box;padding:12px;margin:8px 0;border:1px solid #ccc;border-radius:9px}#messages{height:400px;overflow:auto;background:#f8fafc;padding:10px}.msg{padding:9px;margin:7px;border-radius:9px;white-space:pre-wrap}.user{background:#dbeafe}.ai{background:#e5e7eb}pre{white-space:pre-wrap;background:#111827;color:#fff;padding:12px;direction:ltr;text-align:left;overflow:auto}.bar{height:24px;background:#ddd;border-radius:8px;overflow:hidden}.fill{height:100%;background:#2563eb;color:#fff;text-align:center;line-height:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px}.small{font-size:13px;color:#5b6470}.danger{background:#fee2e2}.layout{display:grid;grid-template-columns:240px 1fr;gap:14px}.sidebar{position:sticky;top:10px;height:fit-content}.chatItem{display:block;width:100%;text-align:right;background:#f8fafc;margin:4px 0;padding:9px;border-radius:8px}.chatItem.active{background:#dbeafe}.chatRow{display:flex;gap:4px;align-items:center}.chatRow .chatItem{flex:1}.chatAction{padding:7px 8px;background:#eef2ff}.githubBox{border:1px solid #d1d5db;padding:12px;border-radius:10px;margin-bottom:10px}.githubOut{white-space:pre-wrap;font-size:13px}@media(max-width:800px){.layout{grid-template-columns:1fr}.sidebar{position:static}}.helpBtn{font-size:13px;background:#e0e7ff;color:#1e3a8a;text-decoration:none;padding:6px 10px;border-radius:7px;float:left}.ok{background:#dcfce7}button:disabled{opacity:.55;cursor:not-allowed}</style></head><body><main>
<div class='layout'><aside class='card sidebar'><button id='newChat' type='button'>+ گفتگوی جدید</button><h3>چت‌های اخیر</h3><div id='chatList'></div><hr><div class='githubBox'><b>GitHub</b><p class='small'>اتصال گرافیکی به مخزن</p><input id='githubRepo' value='cognitive-kernel/My-ai' placeholder='owner/repository' style='width:100%;box-sizing:border-box;padding:9px;border:1px solid #ccc;border-radius:8px'><button id='githubConnect' type='button'>اتصال</button><div id='githubStatus' class='small'></div></div></aside><section><h1>My-AI <a class='helpBtn' href='/help#chat' target='_blank'>راهنمای کامل</a></h1><p id='subtitle'>دستیار محلی برای یادگیری، برنامه‌نویسی و بررسی امنیتی</p>
<div class='card'><button id='faBtn' type='button'>فارسی</button><button id='enBtn' type='button'>English</button><select id='voiceLang'><option value='fa-IR'>صدای فارسی</option><option value='en-US'>English voice</option></select></div>
<div class='card'><h2 id='chatTitle'>دستور به دستیار <a class='helpBtn' href='/help#chat' target='_blank'>راهنما</a></h2><div id='messages'></div><textarea id='msg' rows='3' placeholder='مثلاً: پایتون یاد بگیر، بعد یک صفحه ورود بساز و پن‌تست بگیر' onkeydown='if(event.key==="Enter"&&!event.ctrlKey&&!event.shiftKey){event.preventDefault();window.myAiSend();}'></textarea><button type='button' id='sendBtn' onclick='window.myAiSend()'>ارسال</button><button type='button' id='voiceBtn'>گفتار</button><button type='button' id='stopBtn'>توقف صدا</button><p class='small' id='policy'>پیش‌فرض: «پن‌تست» یعنی بررسی و اصلاح. اگر بگویید «فقط گزارش بده» یا «فقط تست بگیر»، فقط گزارش می‌شود. دستور صریح شما همیشه بر پیش‌فرض غلبه دارد.</p></div>
<div class='card'><h2 id='progressTitle'>پیشرفت یادگیری <a class='helpBtn' href='/help#learning' target='_blank'>راهنما</a></h2><div id='dashboard'>در حال بارگذاری...</div></div>
<div class='card'><h2 id='securityTitle'>گزارش امنیتی <a class='helpBtn' href='/help#security' target='_blank'>راهنما</a></h2><div class='grid'><div class='card ok'><b>اصلاح خودکار</b><p>با درخواست صریح شما فعال می‌شود یا طبق پیش‌فرض پن‌تست.</p></div><div class='card danger'><b>گزارش فقط</b><p>با «فقط تست بگیر» یا «فقط گزارش بده» هیچ تغییری در پروژه ایجاد نمی‌شود.</p></div></div></div>
<div class='card'><h2 id='learnTitle'>یادگیری سریع <a class='helpBtn' href='/help#learning' target='_blank'>راهنما</a></h2><button type='button' data-learn='Python'>Python</button><button type='button' data-learn='PHP'>PHP</button><button type='button' data-learn='JavaScript'>JavaScript</button><button type='button' data-learn='Pentest'>Pentest</button><pre id='learnout'></pre></div>
<script>
(function(){
'use strict';
var recognition=null,voiceLocale='fa-IR',uiLang='fa',busy=false,currentSessionId=null;
var T={fa:{sub:'دستیار محلی برای یادگیری، برنامه‌نویسی و بررسی امنیتی',chat:'دستور به دستیار',send:'ارسال',voice:'گفتار',stop:'توقف صدا',progress:'پیشرفت یادگیری',security:'گزارش امنیتی',learn:'یادگیری سریع',ph:'مثلاً: پایتون یاد بگیر، بعد یک صفحه ورود بساز و پن‌تست بگیر',policy:'پیش‌فرض: «پن‌تست» یعنی بررسی و اصلاح. اگر بگویید «فقط گزارش بده» یا «فقط تست بگیر»، فقط گزارش می‌شود. دستور صریح شما همیشه بر پیش‌فرض غلبه دارد.'},en:{sub:'Local assistant for learning, programming and security testing',chat:'Command the assistant',send:'Send',voice:'Voice',stop:'Stop voice',progress:'Learning progress',security:'Security report',learn:'Quick learning',ph:'Example: learn Python, then build a login page and pentest it',policy:'Default: “pentest” means test and remediate. If you say “report only” or “test only”, it only reports. Your explicit command always overrides the default.'}};
function $(id){return document.getElementById(id)}
function add(t,w){var d=document.createElement('div');d.className='msg '+w;d.textContent=t;$('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight}
function setLang(l){uiLang=l;document.documentElement.lang=l;document.documentElement.dir=l==='fa'?'rtl':'ltr';var t=T[l];$('subtitle').textContent=t.sub;$('chatTitle').firstChild.textContent=t.chat;$('sendBtn').textContent=t.send;$('voiceBtn').textContent=t.voice;$('stopBtn').textContent=t.stop;$('progressTitle').firstChild.textContent=t.progress;$('securityTitle').firstChild.textContent=t.security;$('learnTitle').firstChild.textContent=t.learn;$('msg').placeholder=t.ph;$('policy').textContent=t.policy}
async function post(p,b){var r=await fetch(p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});var text=await r.text();var j;try{j=JSON.parse(text)}catch(_){throw Error('HTTP '+r.status+': '+text.slice(0,300))}if(!r.ok)throw Error(j.detail||'HTTP '+r.status);return j}
function renderResult(j){var nl=String.fromCharCode(10),a=j.answer||'';if(j.type==='code'&&j.data)a+=nl+nl+(j.data.code||'');if(j.type==='security'&&j.data){a+=nl+nl;a+=(uiLang==='fa'?'خلاصه: ':'Summary: ')+JSON.stringify(j.data.summary||{});(j.data.findings||[]).forEach(function(f){a+=nl+'['+f.severity+'] '+f.title+' — '+(f.file||'')+':'+(f.line||'')+nl+(uiLang==='fa'?'راهکار: ':'Fix: ')+(f.remediation||'')})}if(j.type==='learning'&&j.data)a+=nl+JSON.stringify(j.data);return a||JSON.stringify(j,null,2)}
async function send(){if(busy)return;var m=$('msg').value.trim();if(!m)return;busy=true;$('sendBtn').disabled=true;add(m,'user');saveLocalHistory();$('msg').value='';try{var j=await post('/chat',{message:m,session_id:currentSessionId});if(j.session_id)currentSessionId=j.session_id;loadSessions();var a=renderResult(j);add(a,'ai');saveLocalHistory();speak(a);loadDash()}catch(e){add('خطا: '+(e.message||String(e)),'ai')}finally{busy=false;$('sendBtn').disabled=false;$('msg').focus()}}
function voiceInput(){var SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){add(uiLang==='fa'?'تشخیص گفتار در این مرورگر پشتیبانی نمی‌شود.':'Speech Recognition is not supported in this browser.','ai');return}recognition=new SR();recognition.lang=voiceLocale;recognition.interimResults=false;recognition.onresult=function(e){$('msg').value=e.results[0][0].transcript;send()};recognition.onerror=function(e){add('Voice error: '+e.error,'ai')};recognition.start()}
function stopVoice(){if(recognition)recognition.stop();if(window.speechSynthesis)speechSynthesis.cancel()}
function speak(t){if(window.speechSynthesis){speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(t);u.lang=voiceLocale;speechSynthesis.speak(u)}}
function saveLocalHistory(){try{var items=[];document.querySelectorAll('#messages .msg').forEach(function(x){items.push({role:x.classList.contains('user')?'user':'assistant',content:x.textContent})});localStorage.setItem('myai_chat_history',JSON.stringify(items.slice(-200)))}catch(e){}} 
function renderHistory(items){var box=$('messages');if(!box)return;box.innerHTML='';(items||[]).forEach(function(x){add(x.content,x.role==='user'?'user':'ai')})}
function loadLocalHistory(){try{var raw=localStorage.getItem('myai_chat_history')||'[]';var items=JSON.parse(raw);if(Array.isArray(items)&&items.length){renderHistory(items);return true}}catch(e){console.error('local history',e)}return false}
function escHtml(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
async function loadSessions(){try{var r=await fetch('/chat/sessions?x='+Date.now(),{cache:'no-store'}),j=await r.json(),list=j.sessions||[],h='';list.forEach(function(s){h+='<div class="chatRow"><button type="button" class="chatItem '+(Number(s.id)===Number(currentSessionId)?'active':'')+'" data-chat-id="'+s.id+'">'+(s.pinned?'📌 ':'')+escHtml(s.title||'گفتگوی جدید')+'</button><button type="button" class="chatAction" data-rename-id="'+s.id+'" title="تغییر نام">✎</button><button type="button" class="chatAction" data-pin-id="'+s.id+'" title="پین/برداشتن پین">📌</button><button type="button" class="chatAction" data-delete-id="'+s.id+'" title="حذف">×</button></div>'});$('chatList').innerHTML=h||'<div class="small">هنوز چتی نیست</div>';document.querySelectorAll('[data-chat-id]').forEach(function(b){b.addEventListener('click',function(){selectChat(Number(this.getAttribute('data-chat-id')))} )});document.querySelectorAll('[data-rename-id]').forEach(function(b){b.addEventListener('click',function(e){e.stopPropagation();renameChat(Number(this.getAttribute('data-rename-id')))} )});document.querySelectorAll('[data-pin-id]').forEach(function(b){b.addEventListener('click',function(e){e.stopPropagation();pinChat(Number(this.getAttribute('data-pin-id')))} )});document.querySelectorAll('[data-delete-id]').forEach(function(b){b.addEventListener('click',function(e){e.stopPropagation();deleteChat(Number(this.getAttribute('data-delete-id')))} )});if(currentSessionId===null&&list.length)await selectChat(Number(list[0].id))}catch(e){$('chatList').textContent='خطا: '+e.message}}
async function selectChat(id){try{currentSessionId=Number(id);var r=await fetch('/chat/history?session_id='+encodeURIComponent(id)+'&limit=200',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.detail||'HTTP '+r.status);renderHistory(j.messages||[]);await loadSessions()}catch(e){$('messages').innerHTML='';add('خطا در بارگذاری گفتگو: '+e.message,'ai')}}
async function renameChat(id){var name=prompt('نام جدید گفتگو:');if(!name||!name.trim())return;try{var r=await fetch('/chat/sessions/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:name.trim()})});if(!r.ok)throw Error((await r.text()).slice(0,300));await loadSessions()}catch(e){alert('خطا: '+e.message)}}
async function pinChat(id){try{var j=await post('/chat/sessions/'+id+'/pin',{});await loadSessions()}catch(e){alert('خطا: '+e.message)}}
async function deleteChat(id){if(!confirm('این گفتگو و تاریخچه آن حذف شود؟'))return;try{var r=await fetch('/chat/sessions/'+id,{method:'DELETE'});if(!r.ok)throw Error((await r.text()).slice(0,300));if(currentSessionId===Number(id)){currentSessionId=null;renderHistory([])}await loadSessions()}catch(e){alert('خطا: '+e.message)}}
async function connectGithub(){var repo=$('githubRepo').value.trim();if(!repo)return;$('githubStatus').textContent='در حال اتصال...';try{var r=await fetch('/git/repo?repository='+encodeURIComponent(repo),{cache:'no-store'}),text=await r.text(),j;try{j=JSON.parse(text)}catch(_){throw Error('HTTP '+r.status+': '+text.slice(0,300))}if(!r.ok)throw Error(j.detail||j.error||('HTTP '+r.status));$('githubStatus').textContent='متصل: '+(j.full_name||repo)+(j.private?' | خصوصی':' | عمومی')+(j.authenticated?' | احراز هویت فعال':' | بدون توکن (فقط عمومی)')}catch(e){$('githubStatus').textContent='خطا: '+e.message}}
async function newChat(){var j=await post('/chat/sessions',{message:'گفتگوی جدید'});currentSessionId=j.id;renderHistory([]);loadSessions();$('msg').focus()}
async function learn(lang){$('learnout').textContent='در حال مطالعه '+lang+'... این مرحله ممکن است چند دقیقه زمان ببرد.';try{var j=await post('/learning/step',{language:lang});$('learnout').textContent=JSON.stringify(j,null,2);loadDash()}catch(e){$('learnout').textContent='خطا: '+(e.message||String(e));loadDash()}}
async function loadDash(){try{var rr=await Promise.all([fetch('/learning/status',{cache:'no-store'}),fetch('/scheduler/status',{cache:'no-store'})]);var j=await rr[0].json(),s=await rr[1].json(),rows=j.languages||[],stage=s.stage||'idle',topic=s.current_topic||'',live=s.running?'در حال یادگیری':'متوقف';var h='<div class="card '+(s.error?'danger':'ok')+'"><b>وضعیت زنده:</b> '+live+' | <b>مرحله:</b> '+stage+(topic?' | <b>موضوع:</b> '+topic:'')+(s.error?'<div>خطا: '+s.error+'</div>':'')+'</div><table style="width:100%"><tr><th>زبان / Language</th><th>موضوعات</th><th>درصد</th><th>میانگین</th></tr>';rows.forEach(function(x){h+='<tr><td>'+x.language+'</td><td>'+x.completed_topics+'/'+x.total_topics+'</td><td>'+x.progress_percent+'%<div class="bar"><div class="fill" style="width:'+x.progress_percent+'%">'+x.progress_percent+'%</div></div></td><td>'+x.average_score+'%</td></tr>'});h+='</table>';if(s.last_result&&s.last_result.status==='completed'){h+='<p class="small">آخرین موضوع با موفقیت تکمیل شد.</p>'}$('dashboard').innerHTML=h}catch(e){$('dashboard').textContent='خطا: '+(e.message||String(e))}}
function init(){
$('faBtn').addEventListener('click',function(){setLang('fa')});$('enBtn').addEventListener('click',function(){setLang('en')});$('voiceLang').addEventListener('change',function(){voiceLocale=this.value});$('voiceBtn').addEventListener('click',voiceInput);$('stopBtn').addEventListener('click',stopVoice);$('sendBtn').addEventListener('click',send);$('msg').addEventListener('keydown',function(event){if(event.key==='Enter'&&!event.ctrlKey&&!event.shiftKey){event.preventDefault();send()}});document.querySelectorAll('[data-learn]').forEach(function(b){b.addEventListener('click',function(){learn(this.getAttribute('data-learn'))})});setLang('fa');loadSessions();loadDash();setInterval(loadDash,2000);$('newChat').addEventListener('click',newChat);$('githubConnect').addEventListener('click',connectGithub);connectGithub();$('msg').focus()}
window.myAiSend=send;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
</script></section></div></main></body></html>"""
def page(): return HTML
